---
name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_CREDENTIALS_PATH: ${{ secrets.GOOGLE_CREDENTIALS_PATH }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_API_URL: ${{ secrets.GROQ_API_URL }}
          GROQ_MODEL: ${{ secrets.GROQ_MODEL }}
          GROQ_MAX_TOKENS: ${{ secrets.GROQ_MAX_TOKENS }}
          GROQ_CONTEXT_MAX_TOKENS: ${{ secrets.GROQ_CONTEXT_MAX_TOKENS }}
        run: |
          python -m unittest discover -s tests
